### Site info:
title: Joao Ramos
tagline: Personal Blog
author: Joao Ramos
email: joao.ramos@dcc.fc.up.pt
description: "Joao Ramos - Personal Blog"
keywords: "Joao Ramos, Blog"
baseurl: ""
url: "http://joaoramos.me"
locale: en_US

### Personal info and site tools info:
github_username:  JoaoM10
disqus_shortname: JoaoM10
favicon:     "/images/favicon.ico"
aboutme: Hi, this is my personal blog.
aboutme_photo: https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xaf1/v/t1.0-9/523270_499122733431321_1594939973_n.jpg?oh=28d1906a4363fe330b548a5fa7a02784&oe=55B2D994&__gda__=1433435461_7e798b791726eccbf14ce10fd4984258


### Site setting:
ShowContactInfo: "True"
default_column: "two"
default_locale: "en"

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Joao Ramos
      href: http://joaoramos.me
      title: Joao Ramos - Personal Blog


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
